development:
  adapter: postgresql
  encoding: unicode
  database: school_development
  pool: 5
  username: przemyslaw
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: school_test
  pool: 5
  username: przemyslaw
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: school_test
  pool: 5
  username: przemyslaw
  password: