# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db44b2f180bc4054193d7eb30648a518cbcbacd1393d2b0ef9a91f2f294fde27a9918ea440066c2cc81bae544257b058cd2322577b45f68bdb67f7150f7aa6ef

test:
  secret_key_base: 4f08ddf583b67ca8067114272048ba7f8754bc935417e2208b00bd7348c27173fb168653ac1cab58181961636ff9f14a699d17e7a862d0f380f5cbf7c41bc48b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
